# Book settings
title: DSCI 513<br>Databases & Data Retrieval
author: Gittu George
logo: lectures/img/dsci513_logo.png

repository:
  url: https://github.com/MDS-Lecture-Notes-513-SQL

latex:
  latex_documents:
    targetname: book.tex

# Execution settings
execute:
  execute_notebooks: "off" # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

build:
  only_build_toc_files: true

# HTML-specific settings
html:
  favicon: "lectures/img/favicon.png" # A path to a favicon image
  navbar_number_sections: false # Add a number to each section in your left navbar
  use_edit_page_button: false # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button: false # Whether to add a link to your repository button
  use_issues_button: false # Whether to add an "open an issue" button
  extra_navbar: Gittu George, MDS 2024<br>Powered by <a href="https://jupyterbook.org">Jupyter Book</a> # Will be displayed underneath the left navbar.
  extra_footer: "" # Will be displayed underneath the footer.
  google_analytics_id: "" # A GA id that can be used to track book views.
  home_page_in_navbar: true # Whether to include your home page in the left Navigation Bar
  baseurl: "" # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
parse:
  myst_enable_extensions:
    - html_image
    - dollarmath